# Site wide configuration

title: #
locale: en_IN
url: https://alokssingh.github.io
# Jekyll configuration
theme: jekyll-theme-cayman
permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gis
#plugins:
#  - jekyll-gist
plugins: ['jekyll-twitter-plugin']
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

# Site owner
owner:
  name: Alok Singh
  avatar:  new_pic.png #IMG-6716.jpg #try image instead of avatar, try cmlh pic
  position: Graduate Student
  school: National Institute of Technology Silchar
  place: Silchar, Assam, India.
  bio: "Graduate student<br/>National Institute of Technology Silchar, India"
  email: alok.rawat478@gmail.com
  disqus-shortname:
  twitter: singh_ak_
  facebook:  #username
  google:
    scholar: https://scholar.google.com/citations?user=K6ecfUwAAAAJ&hl=en
    plus:  #username
    analytics: # UA-57438847-4
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: alokssingh
  stackoverflow: #username 
  linkedin: alokssingh #username
  researchgate: https://www.researchgate.net/profile/Alok_Singh108
  xing: #username
  instagram: _alokksingh
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]
