# Site wide configuration

title:    Alok Singh
locale: en_IN
url: https://alokssingh.github.io
# Jekyll configuration
theme: jekyll-theme-cayman
permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gis
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from 

#plugins: ['jekyll-twitter-plugin']
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

# Site owner
owner:
  name: Alok Singh
  avatar:  new_pic.png
  position: Senior Research Associate
  school: University of Oxford
  place: Oxford, UK
  #bio: "Doctor of Philosophy<br/>National Institute of Technology Silchar, India"
  email: alok.rawat478@gmail.com
  disqus-shortname: 
  google-scholar: "https://scholar.google.co.in/citations?hl=en&user=K6ecfUwAAAAJ"
  social-network-links:
     ORCID: 0000-0002-2683-0542
  twitter: _im_singh
  #facebook:
  google:
    #google-scholar: K6ecfUwAAAAJ&hl
    #plus:  #username
    #analytics: # UA-57438847-4
    #verify:
    #ad-client:
    #ad-slot:
  bing-verify:
  github: alokssingh
  stackoverflow: #username 
  linkedin: alokssingh #username
  researchgate: "https://www.researchgate.net/profile/Alok-Singh-97"
  xing: #username
  instagram: #_alokksingh
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username


include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]
